info:
  contact: {}
  description: Exhibition Service สำหรับขอจัดการเกี่ยวกับ Exhibition ทั้งการสร้าง
    แก้ไข ลบ exhibition
  title: Exhibition Service API
  version: v0
paths:
  /api/exhibitions:
    get:
      description: Get a list of all exhibitions
      operationId: GetAllExhibitions
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get all exhibitions
      tags:
      - Exhibitions
    post:
      consumes:
      - application/json
      description: Create a new exhibition
      parameters:
      - description: Exhibition data to create
        in: body
        name: requestExhibition
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            type: string
        "400":
          description: Invalid request body
          schema:
            type: string
      summary: Create a new exhibition
      tags:
      - Exhibitions
  /api/exhibitions/{id}:
    delete:
      description: Delete exhibition by ID
      operationId: DeleteExhibition
      parameters:
      - description: Exhibition ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Delete Exhibition Success
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete exhibition by ID
      tags:
      - Exhibitions
    get:
      description: Get exhibition details by ID
      operationId: GetExhibitionByID
      parameters:
      - description: Exhibition ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Get exhibition by ID
      tags:
      - Exhibitions
schemes:
- http
swagger: "2.0"
