definitions:
  helper.APIError:
    properties:
      errorMessage:
        type: string
    type: object
  model.CenterItem:
    properties:
      details:
        $ref: '#/definitions/model.Details'
      previewType:
        type: string
      src:
        type: string
    type: object
  model.Contents:
    properties:
      text:
        items:
          items:
            type: string
          type: array
        type: array
      title:
        type: string
    type: object
  model.Details:
    properties:
      contents:
        items:
          $ref: '#/definitions/model.Contents'
        type: array
      img:
        type: string
    type: object
  model.ExhibitionSection:
    properties:
      _id:
        type: string
      background:
        type: string
      contentType:
        type: string
      exhibitionId:
        type: string
      images:
        items:
          type: string
        type: array
      leftCol:
        $ref: '#/definitions/model.LeftColumn'
      rightCol:
        $ref: '#/definitions/model.RightColumn'
      sectionType:
        type: string
      text:
        type: string
      title:
        type: string
    required:
    - exhibitionId
    - sectionType
    type: object
  model.LeftColumn:
    properties:
      contentType:
        type: string
      image:
        type: string
      imageDescription:
        type: string
      text:
        type: string
      title:
        type: string
    type: object
  model.LeftRightItem:
    properties:
      details:
        $ref: '#/definitions/model.Details'
      previewType:
        type: string
      src:
        type: string
    type: object
  model.RequestCreateExhibition:
    properties:
      endDate:
        type: string
      exhibitionCategories:
        items:
          type: string
        type: array
      exhibitionDescription:
        type: string
      exhibitionName:
        type: string
      exhibitionSectionsID:
        items:
          type: string
        type: array
      exhibitionTags:
        items:
          type: string
        type: array
      isPublic:
        type: boolean
      layoutUsed:
        type: string
      likeCount:
        type: integer
      rooms:
        items:
          $ref: '#/definitions/model.Room'
        type: array
      startDate:
        type: string
      status:
        type: string
      thumbnailImg:
        type: string
      userId:
        $ref: '#/definitions/model.UserID'
      visitedNumber:
        type: integer
    required:
    - endDate
    - exhibitionCategories
    - exhibitionDescription
    - exhibitionName
    - isPublic
    - layoutUsed
    - startDate
    - status
    - thumbnailImg
    - userId
    type: object
  model.RequestCreateExhibitionSection:
    properties:
      background:
        type: string
      contentType:
        type: string
      exhibitionID:
        type: string
      images:
        items:
          type: string
        type: array
      leftCol:
        $ref: '#/definitions/model.LeftColumn'
      rightCol:
        $ref: '#/definitions/model.RightColumn'
      sectionType:
        type: string
      text:
        type: string
      title:
        type: string
    required:
    - exhibitionID
    - sectionType
    type: object
  model.RequestUpdateExhibition:
    properties:
      endDate:
        type: string
      exhibitionCategories:
        items:
          type: string
        type: array
      exhibitionDescription:
        type: string
      exhibitionName:
        type: string
      exhibitionSectionsID:
        items:
          type: string
        type: array
      exhibitionTags:
        items:
          type: string
        type: array
      isPublic:
        type: boolean
      layoutUsed:
        type: string
      rooms:
        items:
          $ref: '#/definitions/model.Room'
        type: array
      startDate:
        type: string
      status:
        type: string
      thumbnailImg:
        type: string
      userId:
        $ref: '#/definitions/model.UserID'
      visitedNumber:
        type: integer
    required:
    - status
    type: object
  model.RequestUpdateExhibitionSection:
    properties:
      background:
        type: string
      contentType:
        type: string
      exhibitionID:
        type: string
      images:
        items:
          type: string
        type: array
      leftCol:
        $ref: '#/definitions/model.LeftColumn'
      rightCol:
        $ref: '#/definitions/model.RightColumn'
      sectionType:
        type: string
      text:
        type: string
      title:
        type: string
    required:
    - exhibitionID
    - sectionType
    type: object
  model.ResponseExhibition:
    properties:
      _id:
        type: string
      endDate:
        type: string
      exhibitionCategories:
        items:
          type: string
        type: array
      exhibitionDescription:
        type: string
      exhibitionName:
        type: string
      exhibitionSections:
        items:
          $ref: '#/definitions/model.ExhibitionSection'
        type: array
      exhibitionTags:
        items:
          type: string
        type: array
      isPublic:
        type: boolean
      layoutUsed:
        type: string
      likeCount:
        type: integer
      rooms:
        items:
          $ref: '#/definitions/model.Room'
        type: array
      startDate:
        type: string
      status:
        type: string
      thumbnailImg:
        type: string
      userId:
        $ref: '#/definitions/model.UserID'
      visitedNumber:
        type: integer
    required:
    - _id
    - exhibitionName
    - layoutUsed
    - status
    - userId
    type: object
  model.ResponseExhibitionSection:
    properties:
      _id:
        type: string
      background:
        type: string
      contentType:
        type: string
      exhibitionID:
        type: string
      images:
        items:
          type: string
        type: array
      leftCol:
        $ref: '#/definitions/model.LeftColumn'
      rightCol:
        $ref: '#/definitions/model.RightColumn'
      sectionType:
        type: string
      text:
        type: string
      title:
        type: string
    required:
    - exhibitionID
    - sectionType
    type: object
  model.ResponseGetExhibitionId:
    properties:
      _id:
        type: string
    required:
    - _id
    type: object
  model.ResponseGetExhibitionSectionId:
    properties:
      _id:
        type: string
    required:
    - _id
    type: object
  model.RightColumn:
    properties:
      contentType:
        type: string
      image:
        type: string
      imageDescription:
        type: string
      text:
        type: string
      title:
        type: string
    type: object
  model.Room:
    properties:
      center:
        items:
          $ref: '#/definitions/model.CenterItem'
        type: array
      left:
        items:
          $ref: '#/definitions/model.LeftRightItem'
        type: array
      mapThumbnail:
        type: string
      right:
        items:
          $ref: '#/definitions/model.LeftRightItem'
        type: array
    type: object
  model.UserID:
    properties:
      firstName:
        type: string
      lastName:
        type: string
      userId:
        type: integer
      username:
        type: string
    required:
    - userId
    type: object
info:
  contact: {}
  description: Exhibition Service สำหรับขอจัดการเกี่ยวกับ Exhibition ทั้งการสร้าง
    แก้ไข ลบ exhibition
  title: Exhibition Service API
  version: v0
paths:
  /api/exhibitions:
    get:
      description: Get a list of all exhibitions data is public only
      operationId: GetExhibitionsIsPublic
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ResponseExhibition'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Get all exhibitions is public
      tags:
      - Exhibitions
    post:
      consumes:
      - application/json
      description: Create a new exhibition data
      parameters:
      - description: Exhibition data to create
        in: body
        name: requestExhibition
        required: true
        schema:
          $ref: '#/definitions/model.RequestCreateExhibition'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/model.ResponseGetExhibitionId'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Create a new exhibition
      tags:
      - Exhibitions
  /api/exhibitions/{id}:
    delete:
      description: Delete exhibition data by exhibitionID
      operationId: DeleteExhibition
      parameters:
      - description: Exhibition ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Delete Exhibition Success
          schema:
            $ref: '#/definitions/model.ResponseGetExhibitionId'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Delete exhibition by ID
      tags:
      - Exhibitions
    get:
      description: Get exhibition data by exhibitionID
      operationId: GetExhibitionByID
      parameters:
      - description: Exhibition ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseExhibition'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Get exhibition by ID
      tags:
      - Exhibitions
    put:
      description: Update exhibition data by exhibitionID
      operationId: UpdateExhibition
      parameters:
      - description: Exhibition ID
        in: path
        name: id
        required: true
        type: string
      - description: Exhibition data to update
        in: body
        name: updateRequest
        required: true
        schema:
          $ref: '#/definitions/model.RequestUpdateExhibition'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseExhibition'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Update exhibition by ID
      tags:
      - Exhibitions
  /api/exhibitions/{id}/like:
    put:
      description: Like exhibition by exhibitionID
      operationId: LikeExhibition
      parameters:
      - description: Exhibition ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseExhibition'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Like exhibition by ID
      tags:
      - Like
  /api/exhibitions/{id}/sections:
    get:
      description: Get Sections By exhibitionID
      operationId: GetSectionsByExhibitionID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ResponseExhibitionSection'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Get Sections By exhibitionID
      tags:
      - Sections
  /api/exhibitions/{id}/unlike:
    put:
      description: unlike exhibition by exhibitionID
      operationId: UnlikeExhibition
      parameters:
      - description: Exhibition ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseExhibition'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Unlike exhibition by ID
      tags:
      - Unlike
  /api/exhibitions/all:
    get:
      description: Get a list of all exhibitions data
      operationId: GetAllExhibitions
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ResponseExhibition'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Get all exhibitions
      tags:
      - Exhibitions
  /api/sections:
    post:
      consumes:
      - application/json
      description: Create a new exhibitionSection data
      parameters:
      - description: ExhibitionSection data to create
        in: body
        name: requestExhibitionSection
        required: true
        schema:
          $ref: '#/definitions/model.RequestCreateExhibitionSection'
      produces:
      - application/json
      responses:
        "201":
          description: Success
          schema:
            $ref: '#/definitions/model.ResponseGetExhibitionSectionId'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Create a new exhibitionSection
      tags:
      - Sections
  /api/sections/{id}:
    delete:
      description: Delete Section data by sectionID
      operationId: DeleteExhibitionSectionByID
      parameters:
      - description: Section ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Delete Section Success
          schema:
            $ref: '#/definitions/model.ResponseGetExhibitionId'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Delete Section by ID
      tags:
      - Sections
    get:
      description: Get exhibition data by sectionID
      operationId: GetExhibitionSectionByID
      parameters:
      - description: Exhibition Section ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseExhibitionSection'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Get exhibitionSection by ID
      tags:
      - Sections
    put:
      description: Update exhibitionSection data by sectionID
      operationId: UpdateExhibitionSection
      parameters:
      - description: ExhibitionSection ID
        in: path
        name: id
        required: true
        type: string
      - description: ExhibitionSection data to update
        in: body
        name: updateRequest
        required: true
        schema:
          $ref: '#/definitions/model.RequestUpdateExhibitionSection'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ResponseExhibition'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Update exhibitionSection by sectionID
      tags:
      - Sections
  /api/sections/all:
    get:
      description: Get a list of all exhibition sections data
      operationId: GetAllExhibitionSections
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.ResponseExhibitionSection'
            type: array
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/helper.APIError'
      summary: Get all exhibitions sections
      tags:
      - Sections
schemes:
- http
swagger: "2.0"
